name: CI/CD Python 3.9.16

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.16
    - name: Install Dependencies
      run: |
        make install
    - name: Linting
      run: |
        make lint
    - name: Unit Tests
      run: |
        make test
